#!/bin/bash

# FIGHT Token Project Summary
echo "🥊 FIGHT Token LayerZero OFT Project Setup Complete!"
echo "====================================================="
echo ""

echo "📁 Project Structure:"
echo "├── 🔧 setup.sh                    # Development environment setup"
echo "├── 🚀 deploy-fight.sh             # Deployment guidance script"
echo "├── 📊 DEPLOYMENT-GUIDE.md         # Complete deployment walkthrough"
echo "├── 📖 FIGHT-README.md             # Project documentation"
echo "├── ⚙️ fight-config.ts             # FIGHT token configuration"
echo "├── 🌐 layerzero.config.ts         # LayerZero OFT settings"
echo "├── 💎 contracts/FightOFT.sol      # EVM FIGHT token contract"
echo "├── 🦀 programs/                   # Solana OFT program"
echo "└── 📋 .env                        # Environment variables"
echo ""

echo "🎯 FIGHT Token Details:"
echo "Name:          FIGHT"
echo "Symbol:        FIGHT"
echo "Total Supply:  10,000,000,000 tokens"
echo "Decimals:      9 (Solana) / 18 (EVM)"
echo "Type:          Omnichain Fungible Token (OFT)"
echo "Chains:        Solana ↔ BSC/Arbitrum/Ethereum"
echo ""

echo "🚀 Next Steps:"
echo "1. Configure your .env file with private keys"
echo "2. Fund your wallets (Solana: 5+ SOL, EVM: native gas tokens)"
echo "3. Run: ./setup.sh (to install correct dependency versions)"
echo "4. Run: ./deploy-fight.sh (for deployment guidance)"
echo "5. Follow the DEPLOYMENT-GUIDE.md for detailed instructions"
echo ""

echo "📚 Key Commands:"
echo "• anchor keys sync -p oft                    # Generate program keypair"
echo "• anchor build -v -e OFT_ID=<PROGRAM_ID>    # Build Solana program"
echo "• pnpm hardhat lz:deploy                     # Deploy EVM contracts"
echo "• pnpm hardhat lz:oapp:wire                  # Connect chains"
echo ""

echo "🌐 Official Links:"
echo "• Website:  https://fight.id"
echo "• Twitter:  https://x.com/JoinFightId"
echo "• Telegram: https://t.me/fightfiofficial"
echo "• Discord:  https://discord.gg/fightid"
echo ""

echo "⚠️  Important Notes:"
echo "• Use Anchor v0.29.0 and Solana CLI v1.17.31 for building"
echo "• Use Solana CLI v1.18.26 for deployment (better experience)"
echo "• Test thoroughly on testnets before mainnet deployment"
echo "• Use multisig wallets for production ownership"
echo ""

echo "🥊 Ready to power the digital economy of combat sports!"
echo "Good luck with your FIGHT token deployment!"